name: Norbert Budincsevity
description: Blogging about some stuff, but mostly just programming
meta_description: "Notes of Norbert Budincsevity"

markdown: redcarpet
highlighter: pygments
logo: https://download.unsplash.com/photo-1433733071959-30cd185d14a8
paginate: 15
baseurl: /
domain_name: 'http://budincsevity.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
