name: Norbert Budincsevity
description: Blogging about some stuff, but mostly just programming
meta_description: "Notes of Norbert Budincsevity"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://budincsevity.github.io'
google_analytics: 'UA-51118211-1'

# Details for the RSS feed generator
url:            'blog url'
author:         'Norbert Budincsevity'
