
title: "Norbert"
title2: "Budincsevity" # default: ""
description: "Notes"
keywords: "Norbert, Budincsevity"
url: http://budincsevity.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch

comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Norbert Budincsevity"
  job      : "Software Engineer"
  bio      : ""
  thumb    : /images/author.jpg
  email    : nbudincsevity@gmail.com
  url      : http://budincsevity.github.io/
  github   : http://github.com/Budincsevity
  twitter  : http://twitter.com/Budincsevity
  linkedin : http://linkedin.com/in/budincsevity

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@Budincsevity"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
